In [1]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)

int64


In [2]:
#2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype == np.float64)

True


In [3]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [4]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
arr = arr.astype(np.float32)
print(arr)

[1. 2. 3. 4. 5.]


In [5]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr = arr.astype(np.float32)
print(arr)

[1.1 2.2 3.3]


In [6]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

In [7]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    return arr.ndim

In [8]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

In [9]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides

In [10]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

In [11]:
#11. Create a function create_zeros_array that takes an integer 'n' as input and returns a NumPy array of zeros with 'n' elements.
def create_zeros_array(n):
    return np.zeros(n)

In [12]:
#12. Write a function create_ones_matrix that takes integers 'rows' and 'cols' as inputs and generates a 2D NumPy array filled with ones of size 'rows x cols'.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

In [13]:
#13. Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified step.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

In [14]:
#14. Design a function generate_linear_space that takes two floats 'start', 'stop', and an integer 'num' as arguments and generates a NumPy array with num equally spaced values between 'start' and 'stop' (inclusive).
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

In [15]:
#15. Create a function create_identity_matrix that takes an integer 'n' as input and generates a square identity matrix of size 'n x n' using numpy.eye.
def create_identity_matrix(n):
    return np.eye(n)

In [16]:
#16. Write a function that takes a Python list and converts it into a NumPy array.
def list_to_array(lst):
    return np.array(lst)

In [17]:
#17. Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data.
arr = np.array([1, 2, 3, 4, 5])
view = arr.view()
print(view)

[1 2 3 4 5]


In [18]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

In [19]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [20]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack(arr_list):
    return np.vstack(arr_list)

In [21]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

In [22]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def equally_spaced_array():
    return np.linspace(0, 1, 10)

In [23]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def log_space_array():
    return np.logspace(0, 3, 5)

In [24]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data)
print(df)

    0   1   2
0  21  21  18
1  56  24  41
2  94  20  84
3  10  77  23
4  42   4  57


In [25]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
def replace_negatives(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

In [26]:
#26. Access the 3rd element from the given NumPy array.
arr = np.array([18, 20, 30, 40, 50])
print(arr[2])

30


In [27]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])

6


In [28]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
print(arr[arr > 5])

[ 8 10  7]


In [29]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])

[3 4 5 6]


In [30]:
#30. Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1:3, 1:3])

[[5 6]
 [8 9]]


In [31]:
#31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_by_indices(arr, indices):
    return arr[indices]

In [32]:
#32. Create a NumPy function that filters elements greater than a threshold from a given array using boolean indexing.
def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

In [33]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_3d_elements(arr, x_indices, y_indices, z_indices):
    return arr[x_indices, y_indices, z_indices]

In [34]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def filter_two_conditions(arr, cond1, cond2):
    return arr[cond1 & cond2]

In [35]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_2d_elements(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

In [36]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = arr + 5
print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3]])  # shape (1, 3)
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # shape (3, 4)
arr1_reshaped = arr1.T  # transpose to shape (3, 1)
result = arr2 * arr1_reshaped
print(result)


[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [38]:
#38. Given a 2D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3, 4]])  # shape (1, 4)
arr2 = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13], [14, 15, 16]])
arr1_reshaped = np.array([[1, 2, 3, 4]])  
arr2_padded = np.pad(arr2, ((0, 0), (0, 1)), mode='constant', constant_values=0)
result = arr2_padded + arr1_reshaped
print(result)

[[ 6  8 10  4]
 [ 9 11 13  4]
 [12 14 16  4]
 [15 17 19  4]]


In [39]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [40]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2], [3, 4]])
result = arr1[:, :2] * arr2
print(result)

[[ 1  4]
 [12 20]]


In [41]:
#41. Calculate column-wise mean for the given array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr, axis=0))

[2.5 3.5 4.5]


In [42]:
#42. Find maximum value in each row of the given array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr, axis=1))

[3 6]


In [43]:
#43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.argmax(arr, axis=0))

[1 1 1]


In [44]:
# 44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(arr, window_size):
    result = []
    for row in arr:
        convolved = np.convolve(row, np.ones(window_size), 'valid')
        result.append(convolved)
    return np.array(result)

result = moving_sum(arr, window_size=2)
print(result)

[[ 3.  5.]
 [ 9. 11.]]


In [45]:
#45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
print(np.all(arr % 2 == 0, axis=0))

[False False False]


In [46]:
#46. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr + 5)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [47]:
#47. Create a function that takes a matrix as input and returns the flattened array.
def flatten_matrix(matrix):
    return matrix.flatten()

In [48]:
#48. Write a function that concatenates two given arrays along a specified axis.
def concat_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

In [49]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.
def split_array(arr, indices, axis=0):
    return np.split(arr, indices, axis=axis)

In [50]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
def modify_array(arr, indices_to_insert, values_to_insert, indices_to_delete):
    arr = np.insert(arr, indices_to_insert, values_to_insert)
    arr = np.delete(arr, indices_to_delete)
    return arr

In [51]:
#51. Create a NumPy array 'arr1' with random integers and another array 'arr2' with integers from 1 to 10. Perform element-wise addition between 'arr1' and 'arr2'.
arr1 = np.random.randint(1, 11, size=(3, 3))
arr2 = np.arange(1, 10).reshape(3, 3)
result = arr1 + arr2
print(result)

[[ 3  4  9]
 [ 8 15 15]
 [10 11 14]]


In [52]:
#52. Generate a NumPy array 'arr1' with sequential integers from 10 to 1 and another array 'arr2' with integers from 1 to 10. Subtract 'arr2' from 'arr1' element-wise.
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2
print(result)

[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [53]:
#53. Create a NumPy array 'arr1' with random integers and another array 'arr2' with integers from 1 to 5. Perform element-wise multiplication between 'arr1' and 'arr2'.
arr1 = np.random.randint(1, 6, size=(3, 3))
arr2 = np.arange(1, 4)  # shape (3,)
arr2_reshaped = arr2.reshape(1, 3)
result = arr1 * arr2_reshaped
print("arr1:\n", arr1)
print("arr2:\n", arr2_reshaped)
print("result:\n", result)

arr1:
 [[2 2 2]
 [5 5 1]
 [4 1 4]]
arr2:
 [[1 2 3]]
result:
 [[ 2  4  6]
 [ 5 10  3]
 [ 4  2 12]]


In [54]:
#54. Generate a NumPy array 'arr1' with even integers from 2 to 10 and another array 'arr2' with integers from 1 to 5. Perform element-wise division of 'arr1' by 'arr2'.
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result = arr1 / arr2
print(result)

[2. 2. 2. 2. 2.]


In [55]:
#55. Create a NumPy array 'arr1' with integers from 1 to 5 and another array 'arr2' with the same numbers reversed. Calculate the exponentiation of 'arr1' raised to the power of 'arr2' element-wise.
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
result = np.power(arr1, arr2)
print(result)

[ 1 16 27 16  5]


In [56]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
def count_substring(arr, substring):
    return np.sum(np.char.find(arr, substring) != -1)

In [57]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.
def extract_uppercase(arr):
    return np.array([s for s in arr if any(c.isupper() for c in s)])

In [58]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

In [59]:
#59. Write a function that concatenates strings in a NumPy array element-wise.
def concat_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

In [60]:
#60. Write a function that finds the length of the longest string in a NumPy array.
def max_string_length(arr):
    return np.max(np.char.str_len(arr))

In [61]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
data = np.random.randint(1, 1001, 100)
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)
print(mean, median, variance, std_dev)

492.82 505.5 83924.82760000002 289.69782118614563


In [62]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
data = np.random.randint(1, 101, 50)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
print(percentile_25, percentile_75)

40.25 81.5


In [63]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.
arr1 = np.random.rand(10)
arr2 = np.random.rand(10)
corr = np.corrcoef(arr1, arr2)[0, 1]
print(corr)

0.12030984482951708


In [64]:
#64. Create two matrices and perform matrix multiplication using NumPy's 'dot' function.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [65]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
data = np.random.randint(10, 1001, 50)
percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)
percentile_90 = np.percentile(data, 90)
quartile_1 = np.percentile(data, 25)
quartile_3 = np.percentile(data, 75)
print(percentile_10, percentile_50, percentile_90, quartile_1, quartile_3)

84.8 462.5 929.7 237.25 787.75


In [66]:
#66. Create a NumPy array of integers and find the index of a specific element.
arr = np.array([1, 2, 3, 4, 5])
index = np.where(arr == 3)[0][0]
print(index)

2


In [67]:
#67. Generate a random NumPy array and sort it in ascending order.
arr = np.random.randint(1, 100, 10)
sorted_arr = np.sort(arr)
print(sorted_arr)

[16 19 23 25 30 34 46 68 74 90]


In [68]:
#68. Filter elements >20 in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
filtered = arr[arr > 20]
print(filtered)

[25 42 30]


In [69]:
#69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
filtered = arr[arr % 3 == 0]
print(filtered)

[12 15]


In [70]:
#70. Filter elements which are >= 20 and <= 40 from a given NumPy array.
arr = np.array([18, 20, 30, 40, 50])
filtered = arr[(arr >= 20) & (arr <= 40)]
print(filtered)

[20 30 40]


In [71]:
#71. For the given NumPy array, check its byte order using the "dtype" attribute byteorder.
arr = np.array([1, 2, 3])
print(arr.dtype.byteorder)

=


In [72]:
#72. For the given NumPy array, perform byte swapping in place using 'byteswap()'.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print(arr)

[16777216 33554432 50331648]


In [73]:
#73. For the given NumPy array, swap its byte order without modifying the original array using newbyteorder().
arr = np.array([1, 2, 3], dtype=np.int32)
new_arr = arr.newbyteorder()
print(new_arr)

[16777216 33554432 50331648]


In [74]:
#74. For the given NumPy array, swap its byte order conditionally based on system endianness using newbyteorder().
arr = np.array([1, 2, 3], dtype=np.int32)
new_arr = arr.newbyteorder('>' if arr.dtype.byteorder == '<' else '<')
print(new_arr)

[1 2 3]


In [75]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using dtype attribute byteorder.
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype.byteorder != '=')

False


In [76]:
#76. Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1 named 'copy_arr' and modify an element in 'copy_arr'. Check if modifying 'copy_arr' affects 'arr1'.
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100
print(arr1, copy_arr)

[ 1  2  3  4  5  6  7  8  9 10] [100   2   3   4   5   6   7   8   9  10]


In [77]:
#77. Create a 2D NumPy array 'matrix' of shape (3, 3) with random integers. Extract a slice 'view_slice' from the matrix. Modify an element in 'view_slice' and observe if it changes the original matrix.
matrix = np.random.randint(1, 10, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 100
print(matrix, view_slice)

[[100   6   2]
 [  5   2   2]
 [  4   3   8]] [[100   6]
 [  5   2]]


In [78]:
#78. Create a NumPy array 'array_a' of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 'view_b' from 'array_a' and broadcast the addition of 5 to 'view_b'. Check if it alters the original 'array_a'.
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :2]
view_b += 5
print(array_a, view_b)

[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]] [[ 6  7]
 [ 9 10]]


In [79]:
#79. Create a NumPy array 'orig_array' of shape (2, 4) with values from 1 to 8. Create a reshaped view 'reshaped_view' of shape (4, 2) from 'orig_array'. Modify an element in 'reshaped_view' and check if it reflects changes in the original 'orig_array'.
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 100
print(orig_array, reshaped_view)

[[100   2   3   4]
 [  5   6   7   8]] [[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [80]:
#80. Create a NumPy array 'data' of shape (3, 4) with random integers. Extract a copy 'data_copy' of elements greater than 5. Modify an element in 'data_copy' and verify if it affects the original 'data'.
data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 100
print(data, data_copy)

[[9 8 9 6]
 [7 7 1 1]
 [9 1 9 7]] [100   8   9   6   7   7   9   9   7]


In [81]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
add_result = A + B
sub_result = A - B
print(add_result, sub_result)

[[ 6  8]
 [10 12]] [[-4 -4]
 [-4 -4]]


In [82]:
#82. Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication.
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))
result = np.dot(C, D)
print(result)

[[ 58  77  60 103]
 [ 26  48  38  66]
 [ 28  36  28  48]]


In [83]:
#83. Create a matrix 'E' and find its transpose.
E = np.random.randint(1, 10, size=(3, 3))
transpose_E = np.transpose(E)
print(transpose_E)

[[2 4 1]
 [6 9 7]
 [2 3 2]]


In [84]:
#84. Generate a square matrix 'F' and compute its determinant.
F = np.random.randint(1, 10, size=(3, 3))
det_F = np.linalg.det(F)
print(det_F)

76.0


In [85]:
#85. Create a square matrix 'G' and find its inverse.
G = np.array([[1, 2], [3, 4]])
inverse_G = np.linalg.inv(G)
print(inverse_G)

[[-2.   1. ]
 [ 1.5 -0.5]]
